### PR TITLE
Bump up version v2.4

### PR DESCRIPTION
**Pull request by syohex**
## Related Issue

#385

## Type of Change

Only bump up version

## Checklist

- [x] I have read the **CONTRIBUTING.md** document.
- [x] I have updated the documentation in the **README.md** file if necessary.
- [x] I have added an entry to **CHANGES.md**.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed (using `make test`).

### CODE REVIEW

**Comment by jrblevin** [comment]
Thanks for all of your hard work to get ready for this release!

**Comment by jrblevin** [comment]
I merged and added a [v2.4](https://github.com/jrblevin/markdown-mode/releases/tag/v2.4) tag 👍

**Comment by syohex** [comment]
Thanks. I have added [release note page](https://github.com/jrblevin/markdown-mode/releases/tag/v2.4)

**Comment by jrblevin** [comment]
That is nice. I didn't know about that feature before.

**Pull request merged**
