### PR TITLE
Fix language correcting script

### PR DESCRIPTION
**Pull request by syohex**
- Original code does not return language list. It returns value of kill-buffer
- Original code ignores language which contains space like 'Emacs Lisp'
- Replace space with '-' like 'Emacs Lisp' -> 'Emacs-Lisp'

And update language list.

This is related to #72.
CC: @blaenk

### CODE REVIEW

**Comment by blaenk** [comment]
Good work!

**Comment by jrblevin** [comment]
Great, thanks! I only have one question: Does GitHub expect or require the spaces to be replaced by hyphens? In my limited testing, it seems so. For example, blocks beginning with ```` ``` Emacs-Lisp```` are highlighted but those beginning with  ```` ``` Emacs Lisp```` are not. I can't find this documented anywhere though...

**Comment by blaenk** [comment]
[This](https://github.com/github/linguist/blob/master/test/test_language.rb#L27-L29) seems to show that hyphens are indeed used.

**Comment by jrblevin** [comment]
Thanks for finding that! I think the patch is probably good as is then.

After experimenting some more (in comments), it seems that to use spaces you have to enclose the language name in braces, like this ```` ``` {Emacs Lisp}````.

**Pull request merged**
