### PR TITLE
Fix wrong file name

### PR DESCRIPTION
**Pull request by syohex**
This is related to #140.

### CODE REVIEW

**Comment by jrblevin** [comment]
Thanks!

**Comment by HenryGessau** [comment]
The wrong file name is still showing on the project page, http://jblevins.org/projects/markdown-mode/

**Comment by syohex** [comment]
I suppose that site is not updated. Please check README.md in github

**Comment by jrblevin** [comment]
I updated the incorrect autoload filename on the homepage just now. Thanks for pointing that out.

(I do update that page, but only when a new release is made. That way the documentation there corresponds to the current release version rather than to things in development.)

**Pull request merged**
