### PR TITLE
Improve moving header commands in GFM

### LINKED ISSUE #33: Lines beginning with hash symbol in literal code blocks treated as headers
For the purposes of commands such as `outline-next-visible-heading` and `outline-forward-same-level`, it is not expected that lines beginning with the `#` symbol in literal code blocks be treated as headers.

For example:

    ### Third level ###

    * A list item
    * and another
      with some overhang
       + and a sublist
         with overhang
    - And a third with a different marker

    ### Third level number two ###

    ~~~ {.bash}
    #!/bin/bash

    # In a code block, this shouldn't be a header
    ~~~

    ### Level two again

    followed by some body text

### PR DESCRIPTION
**Pull request by syohex**
Ignore header like statements in code blocks.

I suppose this patch fixes #33 issue. Please review.

markdown-mode

### CODE REVIEW

**Comment by jrblevin** [comment]
Many thanks for this patch. It works for moving between the previous/next headers (of any level), but not yet for moving between headers of the same level (for example, if at level 2, it skip any 3+ headers and move to the next level 2). This gave me some ideas for rewriting the other outline-mode function, so haven't committed it yet, but I hope to work it in as part of a broader patch soon.

**Comment by jrblevin** [comment]
I'm also working on test cases, etc., and I had one possible concern: I wonder if there might be some unexpected consequences of setting code blocks to be level 7 in the `markdown-outline-level` function. I understand the basic logic, since there are at most six levels of ATX-style headings, but this function is also called by some of the font lock and block movement commands. I want to test it a bit more.

**Comment by syohex** [comment]
> but not yet for moving between headers of the same level (for example, if at level 2, it skip any 3+ headers and move to the next level)

Please tell me what's wrong in more detail. I suppose this patched version commands works like such behaviour.

**Comment by jrblevin** [comment]
In other words, the patch works for `markdown-next-visible-heading` and `markdown-previous-visible-heading` but not for `outline-forward-same-level` and `outline-backward-same-level`. Thank you for the patch, but rather the commit a partial fix I am working on a larger rewrite of the code block parsing functions that should improve font lock, heading folding, heading movement, etc. with respect to headers inside code blocks. My plan is to mark code blocks at the syntax analysis stage and then in the font lock and movement stages, we can simply look at the syntax properties rather than rescanning the document for all code blocks. Stay tuned...

**Pull request closed without merging**
