### PR TITLE
Copy markdown-css-paths in the output buffer

### PR DESCRIPTION
**Pull request by syohex**
## Related Issue

#834 (CC: @mattiasb)

## Type of Change

- [x] Improvement (non-breaking change which improves an existing feature)

## Checklist

- [x] I have read the **CONTRIBUTING.md** document.
- [x] I have updated the documentation in the **README.md** file if necessary.
- [x] I have added an entry to **CHANGES.md**.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed (using `make test`).

### CODE REVIEW

**Comment by mattiasb** [comment]
That was fast! Hopefully I'll have time to take a check later today!

**Comment by mattiasb** [comment]
Tested and it seems to work fine!

**Comment by syohex** [comment]
Thanks for checking

**Comment by mattiasb** [comment]
Thanks for writing the code!

**Pull request merged**
